# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1af1ad3e0d6693acbe9960e80fc685742779363c928d8da022e2a1b2ed074942bd3ed6ce3a4dd5416b2a150517814ce3dd522a4d930fb78b815068e75e639c

test:
  secret_key_base: 9055d1d50b189ab55d0994eaf1a64dea9d5613f8992be7a536e95930a13f831585433bbd0f4dd15c92fb5d8693f4b83378b609cec1624e86d7720b759fb1c6a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
